package edu.wustl.cielo.enums

enum ActivityTypeEnum {

    /*New activity*/
    ACTIVITY_NEW_USER,
    ACTIVITY_NEW_PROJECT,
    ACTIVITY_NEW_UPLOAD_DATA,
    ACTIVITY_NEW_UPLOAD_CODE,
    ACTIVITY_NEW_TEAM,
    ACTIVITY_MANUAL_POST,

    /*Updates*/
    /*PROJECT*/
    ACTIVITY_UPDATE_PROJECT_NAME,
    ACTIVITY_UPDATE_PROJECT_DESCRIPTION,
    ACTIVITY_UPDATE_PROJECT_LICENSE,
    ACTIVITY_UPDATE_PROJECT_STATUS,
    ACTIVITY_UPDATE_PROJECT_SHARED,
    ACTIVITY_UPDATE_PROJECT_TEAMS,
    ACTIVITY_UPDATE_PROJECT_CODES,
    ACTIVITY_UPDATE_PROJECT_DATAS,
    ACTIVITY_UPDATE_PROJECT_PUBLICATIONS,
    ACTIVITY_UPDATE_PROJECT_ANNOTATIONS,
    ACTIVITY_UPDATE_PROJECT_COMMENTS,
    ACTIVITY_UPDATE_PROJECT_METADATAS,


    /*Users*/
    ACTIVITY_UPDATE_USER_INSTITUTION,
    ACTIVITY_UPDATE_USER_CONNECTIONS,
    ACTIVITY_UPDATE_USER_PICTURE,
    ACTIVITY_UPDATE_USER_INTERESTS,
    ACTIVITY_UPDATE_USER_EMAIL_ADDRESS
}